name: 'test'

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  TEST: ${{ secrets.test }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
       
      - name: execute py script 
        run: echo $TEST
